### ISSUE TITLE
Problem loading page

### ISSUE THREAD

**Issue by toan2948** [galexrt/docker-zulip#101]
I use the command netstat to check listening and see that zulip (28607/docker-proxy and 28620/docker-proxy) listen on the IP address. 

root@www:~# netstat -ntlp |grep 443
tcp        0      0 137.74.178.2:443        0.0.0.0:*               LISTEN      28607/docker-proxy

root@www:~# netstat -ntlp |grep 80
tcp        0      0 137.74.178.2:80         0.0.0.0:*               LISTEN      28620/docker-proxy

But when I use the browser to access to the entry (chat.dev.com) of the IP address, it shows "Unable to connect" or "the connection is time out".

**Comment by galexrt** [comment]
I have no problems starting the default `docker-compose.yml` and connecting to it.

Do you have a firewall in place that blocks these ports? Are the Docker firewall rules in place that do the port forwarding?

**Comment by toan2948** [comment]
my fault,

my IP address was disconnected from the server, I reconnect and it works. Thank you so much! I wilI go on and disturb you again, I think :)

**Comment by toan2948** [comment]
when I am creating Zulip User, I have filled all info and then clicked Register.
But it show this message:
"
INTERNAL SERVER ERROR

This Zulip server is currently experiencing some technical difficulties. Sorry about that!

The page will reload automatically soon after service is restored.

If you'd like, you can drop us a line to let us know what happened.
"

Could you please grant me some suggestion?

**Comment by toan2948** [comment]
The error log shows this:


root@0b5ed01e0aa2:/var/log/zulip# tail -f errors.log 
    realm = do_create_realm(string_id, realm_name)
  File "./zerver/lib/actions.py", line 3012, in do_create_realm
    admin_realm = get_system_bot(settings.NOTIFICATION_BOT).realm
  File "./zerver/lib/cache.py", line 167, in func_with_caching
    val = func(*args, **kwargs)
  File "./zerver/models.py", line 1496, in get_system_bot
    return UserProfile.objects.select_related().get(email__iexact=email.strip())
  File "/home/zulip/deployments/2018-04-23-19-20-08/zulip-py3-venv/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
zerver.models.DoesNotExist: UserProfile matching query does not exist.

**Comment by toan2948** [comment]
After I remove all volumes, change other admin email and run docker-compose again, 

the error log is like below:

root@2ea6cff682f6:/var/log/zulip# tail -f errors.log 
    if mail.send() == 0:
  File "/home/zulip/deployments/2018-04-23-19-20-08/zulip-py3-venv/lib/python3.5/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/zulip/deployments/2018-04-23-19-20-08/zulip-py3-venv/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 111, in send_messages
    sent = self._send(message)
  File "/home/zulip/deployments/2018-04-23-19-20-08/zulip-py3-venv/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 127, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.5/smtplib.py", line 876, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'kg@germantom.com': (454, b'4.7.1 <kg@germantom.com>: Relay access denied')}

**Comment by galexrt** [comment]
@toan2948 The last error message says that your SMTP is denying mail relay access (aka you are not allowed to send mail for this domain probably from the SMTP server) for this domain.
You need to use a domain which is allowed to send mails through the SMTP server you set in the env variables.

**Comment by timabbott** [comment]
This error: https://github.com/galexrt/docker-zulip/issues/101#issuecomment-386528238 comes from the first-time database initialization not having been run; I got into that state by trying to rebuild the database  from scratch for testing with `rm -rf /opt/docker/zulip/postgresql`, which isn't correct (you need to also remove the stamp for whether the DB has been initialized in the `zulip` image).

And the email thing is an SMTP configuration problem.

So I'm closing this as not having an actual problem we can resolve in the main project.
