### ISSUE TITLE
Set persistent storage for the /home/zulip/uploads directory in kubernetes configuration

### ISSUE THREAD

**Issue by timabbott** [galexrt/docker-zulip#115]
As documented in https://zulip.readthedocs.io/en/latest/production/maintain-secure-upgrade.html#backups, we need our docker-compose.yml and kubernetes sample configuration files to declare `/home/zulip/uploads`  as a persistent storage volume.  Otherwise, any files you upload will disappear when restarting the Docker image.

This is probably the most critical issue with the current image.

**Comment by galexrt** [comment]
@timabbott There is already persistence with the current image.. https://github.com/galexrt/docker-zulip/blob/master/Dockerfile#L88 and https://github.com/galexrt/docker-zulip/blob/master/entrypoint.sh#L66-L103.
It is simply linked to `$DATA_DIR`/`/data` dir.

**Comment by timabbott** [comment]
Oh, yeah, I was worried about this in the Kubernetes configuration specifically, but re-reading that, you may be right that this is already working correctly.

If you've tested this recently on Kubernetes, we can probably close this.

**Comment by timabbott** [comment]
OK I've confirmed this is working properly; sorry for the false alarm :)
