### ISSUE TITLE
Problems using mailgun to send mail?

### ISSUE THREAD

**Issue by Galexrt** [Galexrt/docker-zulip#17]
> The 'forget password' email can't be sent.
> I use the mailgun to send email, and it shows that zulip does not calling mailgun to send email.
> - @njuaplusplus

**Comment by Galexrt** [comment]
@njuaplusplus have you set the following env vars in the docker-compose.yml?
* `ZULIP_SETTINGS_EMAIL_HOST` (email host, for example `smtp.example.com`)
* `ZULIP_SETTINGS_EMAIL_HOST_USER` (email host username)
* `ZULIP_SECRETS_email_password` (password of the email host user)

**Comment by njuaplusplus** [comment]
@Galexrt 
Yes, I have set these vars.

And I'm sure that the user and password are correct.

**Comment by pirate** [comment]
Some hosting providers block outgoing traffic to SMTP ports, have you checked to make sure you can telnet from your server to mailgun on port 25?
`telnet mg.yourdomain.com 25`  
You should see some header like:
 `220 yourdomain.com ESMTP Postfix`

**Comment by Galexrt** [comment]
@njuaplusplus If you can connect to the smtp server using telnet like @pirate said.
You can copy the logs out of the container using the `docker cp` command and see if you spot any errors.

This would copy the `/var/log` folder out of the container, `docker cp docker_zulip_zulip_1:/var/log zulip_log`.

**Comment by Galexrt** [comment]
@njuaplusplus I just tested it using my own mailgun account and it worked without a problem.

As I wrote, copy the `/var/log` folder out of the container and check the logs if there are any errors.

Closing this, because it seems to be a server host/network problem.

**Comment by njuaplusplus** [comment]
@pirate
Thank you.
The problem I met is because the first user is not created.
So when I use the forget password to find the password of the first user,
the mailgun of course will not send the email.

**Comment by Galexrt** [comment]
@njuaplusplus See #25. I fixed the user creation script in the latest dev version.
I will merge it soon with the latest version.
