### ISSUE TITLE
Create friendlier README.md

### ISSUE THREAD

**Issue by Galexrt** [Galexrt/docker-zulip#21]
If anyone has some ideas on making the `README.md` look friendlier and show a bit more info, I'll be thankful for any pull requests. :)

**Comment by Galexrt** [comment]
@cmcneil do you have any ideas on how to make the `README.md` look better?

**Comment by cmcneil** [comment]
Startup from scratch: <link to wiki>. And then on the wiki, I agree with you that explanations of all the environmental vars would be good. 

You could also just put the contents of the wiki page front and center in the Readme. I think I definitely expect github Readmes to tell you how to get it running from scratch. (i.e. "You need docker at least vX, and docker-compose at least vX. Then run these commands")

After I get this actually running, I'd be happy to write it up :p.

**Comment by Galexrt** [comment]
@cmcneil Thanks for tipp! I'll try my best. :)

**Comment by Galexrt** [comment]
I added a new README.md and added some more wiki pages with better explanations. I'm working on some more wiki pages about the setup process.

@cmcneil Could you maybe give me some feedback about the new wiki pages and the new README.md?
