### ISSUE TITLE
ERROR:  permission denied to create extension "tsearch_extras"

### ISSUE THREAD

**Issue by cmcneil** [Galexrt/docker-zulip#22]
I seem to have dug up another issue. I don't know very much about docker, perhaps the yml needs to be modified to grant root access in the zulip container?

STEPS TO REPRODUCE:
----------------------------------
- Stop and remove all docker containers.
- Clone a fresh repository.
- Make the following changes to `docker-compose.yml`
  - s/example\.com/mydomain\.org/g
  - Switch the ports from 80:80 -> 8080:80, and 443:443 -> 8443:443, to expose zulip on different host ports.
- Run `docker-compose up` (as root)

VERSION INFO:
----------------------
- Docker version 1.8.3, build f4bf5c7
- docker-compose version: 1.5.0rc1
- Host System(I can't imagine this is relevant): Linux leviathan 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

ERROR LINES:
--------------------
```
zulip_1     | django.db.utils.InternalError: could not open dictionary file "/usr/share/postgresql/9.4/tsearch_data/en_us.dict": No such fil
e or directory
zulip_1     | 
zulip_1     | Zulip migration failed.
dockerzulip_zulip_1 exited with code 1
```
*Probable Root Cause:*
```
zulip_1     | ERROR:  permission denied to create extension "tsearch_extras"
zulip_1     | HINT:  Must be superuser to create this extension.
```
FULL ERROR OUTPUT:
---------------------------------
```
zulip_1     | Setting up database settings and server ...
database_1  | 2015-10-22 02:00:06 UTC [84-1] zulip@zulip ERROR:  permission denied to create role
database_1  | 2015-10-22 02:00:06 UTC [84-2] zulip@zulip STATEMENT:  CREATE USER zulip;
zulip_1     | Waiting for database server to allow connectionsERROR:  permission denied to create role
zulip_1     | ALTER ROLE
database_1  | 2015-10-22 02:00:06 UTC [84-3] zulip@zulip ERROR:  database "zulip" already exists
database_1  | 2015-10-22 02:00:06 UTC [84-4] zulip@zulip STATEMENT:  CREATE DATABASE zulip OWNER=zulip;
database_1  | 2015-10-22 02:00:06 UTC [84-5] zulip@zulip ERROR:  schema "zulip" already exists
database_1  | 2015-10-22 02:00:06 UTC [84-6] zulip@zulip STATEMENT:  CREATE SCHEMA zulip AUTHORIZATION zulip;
zulip_1     | ERROR:  database "zulip" already exists
zulip_1     | ERROR:  schema "zulip" already exists
database_1  | 2015-10-22 02:00:06 UTC [85-1] zulip@zulip ERROR:  permission denied to create extension "tsearch_extras"
database_1  | 2015-10-22 02:00:06 UTC [85-2] zulip@zulip HINT:  Must be superuser to create this extension.
database_1  | 2015-10-22 02:00:06 UTC [85-3] zulip@zulip STATEMENT:  CREATE EXTENSION tsearch_extras SCHEMA zulip;
zulip_1     | ERROR:  permission denied to create extension "tsearch_extras"
zulip_1     | HINT:  Must be superuser to create this extension.
zulip_1     | Database setup done.
zulip_1     | Checking zulip config ...
zulip_1     | Starting zulip migration ...
zulip_1     | Operations to perform:
zulip_1     |   Synchronize unmigrated apps: staticfiles, pipeline
zulip_1     |   Apply all migrations: confirmation, sessions, guardian, zerver, sites, auth, contenttypes                           [37/385]
zulip_1     | Synchronizing apps without migrations:
zulip_1     |   Creating tables...
zulip_1     |     Running deferred SQL...
zulip_1     |   Installing custom SQL...
zulip_1     | Running migrations:
zulip_1     |   Rendering model states... DONE
database_1  | 2015-10-22 02:00:10 UTC [88-1] zulip@zulip ERROR:  could not open dictionary file "/usr/share/postgresql/9.4/tsearch_data/en_u
s.dict": No such file or directory
database_1  | 2015-10-22 02:00:10 UTC [88-2] zulip@zulip STATEMENT:  
database_1  |   CREATE TEXT SEARCH DICTIONARY english_us_hunspell
database_1  |     (template = ispell, DictFile = en_us, AffFile = en_us, StopWords = zulip_english);
database_1  |   CREATE TEXT SEARCH CONFIGURATION zulip.english_us_search (COPY=pg_catalog.english);
database_1  |   ALTER TEXT SEARCH CONFIGURATION zulip.english_us_search
database_1  |     ALTER MAPPING FOR asciiword, asciihword, hword_asciipart, word, hword, hword_part
database_1  |     WITH english_us_hunspell, english_stem;
database_1  | 
database_1  |   CREATE FUNCTION escape_html(text) RETURNS text IMMUTABLE LANGUAGE 'sql' AS $$
database_1  |     SELECT replace(replace(replace(replace(replace($1, '&', '&amp;'), '<', '&lt;'),
database_1  |                                    '>', '&gt;'), '"', '&quot;'), '''', '&#39;');
database_1  |   $$ ;
database_1  | 
database_1  |   ALTER TABLE zerver_message ADD COLUMN search_tsvector tsvector;
database_1  |   CREATE INDEX zerver_message_search_tsvector ON zerver_message USING gin(search_tsvector);
database_1  |   ALTER INDEX zerver_message_search_tsvector SET (fastupdate = OFF);
database_1  | 
database_1  |   CREATE TABLE fts_update_log (id SERIAL PRIMARY KEY, message_id INTEGER NOT NULL);
database_1  |   CREATE FUNCTION do_notify_fts_update_log() RETURNS trigger LANGUAGE plpgsql AS
database_1  |     $$ BEGIN NOTIFY fts_update_log; RETURN NEW; END $$;
database_1  |   CREATE TRIGGER fts_update_log_notify AFTER INSERT ON fts_update_log
database_1  |     FOR EACH STATEMENT EXECUTE PROCEDURE do_notify_fts_update_log();
database_1  |   CREATE FUNCTION append_to_fts_update_log() RETURNS trigger LANGUAGE plpgsql AS
database_1  |     $$ BEGIN INSERT INTO fts_update_log (message_id) VALUES (NEW.id); RETURN NEW; END $$;
database_1  |   CREATE TRIGGER zerver_message_update_search_tsvector_async
database_1  |     BEFORE INSERT OR UPDATE OF subject, rendered_content ON zerver_message
database_1  |     FOR EACH ROW EXECUTE PROCEDURE append_to_fts_update_log();
database_1  | 
zulip_1     |   Applying zerver.0001_initial...Traceback (most recent call last):                                                    [0/385]
zulip_1     |   File "/home/zulip/deployments/current/manage.py", line 24, in <module>
zulip_1     |     execute_from_command_line(sys.argv)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
zulip_1     |     utility.execute()
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
zulip_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
zulip_1     |     self.execute(*args, **cmd_options)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
zulip_1     |     output = self.handle(*args, **options)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 221, in handle
zulip_1     |     executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 110, in migrate
zulip_1     |     self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 148, in apply_migration
zulip_1     |     state = migration.apply(state, schema_editor)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 115, in apply
zulip_1     |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 102, in database_forwards
zulip_1     |     self._run_sql(schema_editor, self.sql)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 127, in _run_sql
zulip_1     |     schema_editor.execute(statement, params=None)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
zulip_1     |     cursor.execute(sql, params)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
zulip_1     |     return self.cursor.execute(sql, params)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
zulip_1     |     six.reraise(dj_exc_type, dj_exc_value, traceback)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
zulip_1     |     return self.cursor.execute(sql)
zulip_1     |   File "/home/zulip/deployments/2015-10-21-23-07-49/zerver/lib/db.py", line 23, in execute
zulip_1     |     return wrapper_execute(self, super(TimeTrackingCursor, self).execute, query, vars)
zulip_1     |   File "/home/zulip/deployments/2015-10-21-23-07-49/zerver/lib/db.py", line 11, in wrapper_execute
zulip_1     |     return action(sql, params)
zulip_1     | django.db.utils.InternalError: could not open dictionary file "/usr/share/postgresql/9.4/tsearch_data/en_us.dict": No such fil
e or directory
zulip_1     | 
zulip_1     | Zulip migration failed.
dockerzulip_zulip_1 exited with code 1
```

**Comment by Galexrt** [comment]
This seems like an error with an older version of the `quay.io/galexrt/zulip-postgresql-tsearchextras`.
Because the errors you give use **postgres version 9.4** and not like in the `quay.io/galexrt/zulip-postgresql-tsearchextras` image **postgres version **9.3**.
Can 
Can you try to start over with removing your current data/volume folders and repull both images?
`docker pull quay.io/galexrt/zulip-postgresql-tsearchextras:latest`
Or are you using an "external"/different postgres container/version?

**Comment by Galexrt** [comment]
@cmcneil This error got fixed in the latest version.

**Comment by cmcneil** [comment]
Thanks for the lightning responses! ^.^

**Comment by Galexrt** [comment]
@cmcneil I fixed all current errors in the **new new v1.3.7 version**.

The image is getting build right now. You can check the build status here [galexrt/zulip - Quay.io](https://quay.io/repository/galexrt/zulip )

**Comment by cmcneil** [comment]
@Galexrt 
Hm, are you sure this is fixed? I'm still getting the same error.

More Detailed Steps to Reproduce
----------------------------------------------
*As Root*
- Stop and remove all docker containers.
  - `docker stop $(docker ps -a -q)`
  - `docker rm $(docker ps -a -q)`
- Clone a fresh repository.
  - `git clone https://github.com/Galexrt/docker-zulip.git` (master, right?)
- Make the following changes to `docker-compose.yml`
  - s/example\.com/mydomain\.org/g
  - Switch the ports from 80:80 -> 8080:80, and 443:443 -> 8443:443, to expose zulip on different host ports.
- Run `docker-compose up` (as root)

**Comment by Galexrt** [comment]
@cmcneil Please wait until the new builds is finally ready.
You can see the build status here https://quay.io/repository/galexrt/zulip
It will take some time to build, but after the builds are ready it will work, I currently have a self built version running without any problems. ;)
See my current running zulip instance https://zulip.zerbytes.net/ using the latest version.
I'm sorry about the builds taking so long.
**Don't forget you have to repull the `quay.io/galexrt/zulip` and `quay.io/galexrt/zulip-postgresql-tsearchextras` image.**

**Comment by Galexrt** [comment]
@cmcneil If you need any help or have any other problems, you can hit me up on the IRC channel `#docker-zulip` on freenode. :)

**Comment by cmcneil** [comment]
Yep! It resolved after pulling the new builds!

**Comment by Galexrt** [comment]
@cmcneil Currently the "real" new images are getting build, I just saw that `quay.io` had network problems and I don't think that the docker hub has already build the images.
On the docker hub the builds take like 30-45 minutes and on Quay.io they take just like 10-20 minutes, but Quay.io had some network troubles when the builds were started so they were a bit delayed. Please repull when all builds are through again. Thanks!

**Comment by Galexrt** [comment]
@cmcneil I just checked quay.io about the progress on the builds
The builds are going slowly through. The builds should be ready in like one hour..

**Comment by Galexrt** [comment]
@cmcneil I just wanted to inform you, that the build is now ready! You can repull the newest version now. :)

**Comment by cmcneil** [comment]
@Galexrt Cool, thanks! I do actually get a running instance now. (https://convox.org:8443)
It's still not exactly working, but I'm guessing that this is an issue with my own configuration. I'll ask in IRC when I work on it later :+1:

**Comment by Galexrt** [comment]
@cmcneil Okay, looking forward to hear from you on IRC.
I hope that I can help you with your configuration. :)
Have you checked out the newly added wiki pages? [Wiki page - Configuration](https://github.com/Galexrt/docker-zulip/wiki/Configuration)

**Comment by Galexrt** [comment]
@cmcneil I just went to your Zulip instance and I think that I already know you get no login page.
Can you please reclone the repo, configure the `docker-compose.yml` with your configuration again and check if it's working then?
If you still get no login form, please create a new ticket.

**Comment by cmcneil** [comment]
@Galexrt Hm, I did that, and still get no login form. Made a ticket.

**Comment by pringtest** [comment]
I managed to deploy Zulip Docker with RDS Postgres Aurora (v14.3). The error mentioned in this topic is actually due to Postgres lacking the extension that Django requires, which is "tsearch_extras" (https://github.com/zulip/zulip/issues/467).

Since Django was used during DB initialization, I commented out some lines in the entrypoint.sh file in the "bootstrappingEnvironment" function. Then, I created a new image with these changes. Below are the lines that I commented out:

# zulipFirstStartInit
# zulipMigration

Before that, I performed a database backup from the Postgres container (v14.0) that running from the docker compose and restored it to RDS Postgres Aurora (v14.3).

I then ran the Docker Compose again using the new image, with the database host, password, and user pointing to RDS Postgres.

Done.
