### ISSUE TITLE
Finish wiki page for ZULIP_SETTINGS_ Vars

### ISSUE THREAD

**Issue by Galexrt** [Galexrt/docker-zulip#26]
https://github.com/Galexrt/docker-zulip/wiki/ZULIP_SETTINGS_*-Vars

**Comment by njuaplusplus** [comment]
> Description: Zulip admin domain (I think everybody in this domain is an admin after registering, but I'm not 100% sure)

I tried this, and find it's not true.

I set the `ZULIP_SETTINGS_ADMIN_DOMAIN` to 'qq.com', 
and register 2 accounts using different xxx.qq.com,
and only the one set by `ZULIP_SETTINGS_ZULIP_ADMINISTRATOR` is admin

**Comment by Galexrt** [comment]
@njuaplusplus Could you give me some feedback about the wiki pages?
