### ISSUE TITLE
ZULIP_SETTINGS_* bools are inserted as strings

### ISSUE THREAD

**Issue by Galexrt** [Galexrt/docker-zulip#27]
**Example**:
In `docker-compose.yml`:
`ZULIP_SETTINGS_EMAIL_US_TLS=True`
In `/etc/zulip/settings.py`:
`ZULIP_SETTINGS_EMAIL_US_TLS = "True"`
Should be:
`ZULIP_SETTINGS_EMAIL_US_TLS = True`

***

@decker502 I created a ticket for the bug.

**Comment by Galexrt** [comment]
Fixed in d116b779457136810df1acbe0b95f45ecf263917.

**Comment by decker502** [comment]
I have tried it, and it works. Thank @Galexrt for you patient :)
