### ISSUE TITLE
Camo's service mandatory?

### ISSUE THREAD

**Issue by eduherraiz** [Galexrt/docker-zulip#43]
I can't see camo's reference in installation zulip documentation.
Could you document why did you included and his use?
Is optional?

**Comment by Galexrt** [comment]
@eduherraiz Camo is used in someway by zulip, but I haven't yet used it "actively" in the container (`docker-compose.yml`).
See here https://github.com/zulip/zulip/blob/59dfec8f8b151b3780c848eb5e69eed3882bc155/zproject/settings.py#L478-L484 and https://github.com/zulip/zulip/blob/59dfec8f8b151b3780c848eb5e69eed3882bc155/puppet/zulip/manifests/camo.pp.

**Comment by Galexrt** [comment]
@eduherraiz I removed camo from the `docker-compose.yml` and I research further if and how Camo is required for zulip.

**Comment by eduherraiz** [comment]
Thank you @Galexrt.
I'm working in a different kubernetes definition based in your work. Let me test it a bit more and I will share it.
BTW good work!

**Comment by Galexrt** [comment]
@eduherraiz That's good to hear! Looking forward to see a pull request from you. :+1:
