### ISSUE TITLE
Add documentation for upgradeing and data persistence

### ISSUE THREAD

**Issue by reyman** [Galexrt/docker-zulip#50]
Hi, 
I'm really interested to try this docker image on my 4GO VPS. 

After installation of this image in production, is it easy to upgrade this image without any lost of data ? I see this is better to manage persistant file using [volume](http://stackoverflow.com/questions/26734402/how-to-upgrade-docker-container-after-its-image-changed) . 

Thanks for your help,
Best.
Sr

**Comment by Galexrt** [comment]
The default way using the `docker-compose.yml` is that in zulip uploaded files are saved in a volume on the host. All cotainers that save persistent data, save it to a volume.

See https://github.com/Galexrt/docker-zulip/blob/master/docker-compose.yml#L51-L52

**Comment by reyman** [comment]
Ok, thanks, so to upgrade the images, what is the best way ?

**Comment by Galexrt** [comment]
You stop your current running instance and then start with the new image(s).

**Comment by reyman** [comment]
Some information about this process for upgrading image of zulip can be added in the documentation perhaps ?

**Comment by Galexrt** [comment]
@reyman Yes you are right. Information about upgrading should be added to the documentation and `README.md`.

**Comment by Galexrt** [comment]
@reyman I added a page about it. See https://github.com/Galexrt/docker-zulip/wiki/Upgrade-Zulip. Is it okay?

**Comment by reyman** [comment]
Great thx :)
There is another point that is not clear for noob like me, the first image init using docker-compose.

After the first pull image, user need to create a file `docker-compose.yml` in project directory and run docker build using `from quay.io/galexrt/zulip:v1.3.9` isn't it ? I [crosspost](https://github.com/docker/compose/issues/2426) on docker, because i find trat documentation is not clear on this point.

**Comment by Galexrt** [comment]
@reyman What do you mean with "... the first image init using docker-compose."?

You don't need to create a new `docker-compose.yml`. There is an example `docker-compose.yml` in the repository.
See https://github.com/Galexrt/docker-zulip/blob/master/docker-compose.yml.

**Comment by reyman** [comment]
Ok  i start to understand. Hum, but when i pull the image like you propose in documentation, this is not clear where the image is uploaded by docker (i'm using ubuntu). If i understand, after pull, and after i found the `docker-compose.yml`, i modify it, build and run the image and that's all ?

**Comment by Galexrt** [comment]
@reyman You don't need to build the image. When you pull it you get a working image.
The `docker-compose.yml` just keeps the settings, when you run the image using `docker-compose up`.
