### ISSUE TITLE
emoij disappears immediately with docker-zulip

### ISSUE THREAD

**Issue by Galexrt** [Galexrt/docker-zulip#53]
See https://github.com/zulip/zulip/issues/316 for backstory.

**Comment by Galexrt** [comment]
@npcode This problem should now be fixed in the latest dev version of the image.
Can you try again with the `quay.io/galexrt/zulip:dev` image?

**Comment by npcode** [comment]
Thanks for the fix but the image does not work. When I run `docker-compose up -d` and open the web page it displays:

```
Loading...

If this message does not go away, please wait a couple seconds and reload the page.
```

The message doesn't disappear even after 30 mins.

**Comment by Galexrt** [comment]
Could you enter the container and post the output of all files in the folder `/var/log/zulip` as a gist?
Enter the container using `docker exec -it ZULIP_CONTAINER_NAME /bin/bash` and use `cat` on the log files in the `/var/log/zulip` please. Thanks!

The logs would really help me fix the problem. :)

**Comment by Galexrt** [comment]
Closing this because it should be fixed now.
