### ISSUE TITLE
How to configure the docker-compose.yml?

### ISSUE THREAD

**Issue by jazzcrack** [Galexrt/docker-zulip#54]
First, I'm new at Docker. So, sorry for my dumb question.

1. I have successfully installed Docker and got the container (docker pull quay.io/galexrt/zulip). 
2. Now, i should configure the docker-compose.yml before run the container. How? Where do i find the docker-compose.yml?

Thx for any help.

**Comment by Galexrt** [comment]
There is a wiki page about configuring the `docker-compose.yml`, see https://github.com/Galexrt/docker-zulip/wiki/Configuration.

You get the docker-compose.yml through downloading a copy of the repo here, see https://github.com/Galexrt/docker-zulip/archive/master.zip

**Comment by jazzcrack** [comment]
What about a step by step tutorial ...

1. docker pull quay.io/galexrt/zulip:v1.3.9
2. ...
3. ...

I don't get it, isn't there somewhere already the docker-compose after "docker pull quay.io/galexrt/zulip:v1.3.9"?

**Comment by Galexrt** [comment]
1. Install docker-compose (see https://docs.docker.com/compose/install/)
2. Download this github repository https://github.com/Galexrt/docker-zulip/archive/master.zip
3. Extract the archive to a folder and enter it
4. Open the ``docker-compose.yml`` in the folder and modify it to your needs. See https://github.com/Galexrt/docker-zulip/wiki/Configuration
5. Run ``docker-compose up`. Now all required containers for zulip are running and zulip should be up and running.

If you need more help, please ask for example in the G+ Docker Community. Thanks!

**Comment by jazzcrack** [comment]
Thx
