### ISSUE TITLE
Docker Zulip Release v1.3.10

### ISSUE THREAD

**Issue by Galexrt** [Galexrt/docker-zulip#58]
Current dev branch: `dev-v1.3.10`

Wait for Zulip to merge the modified scripts and the `dockervoyager.pp` manifest, see https://github.com/zulip/zulip/pull/450.

**Comment by Galexrt** [comment]
I'm going to move the changes from my pull request in the repo so I can finally release it.

**Comment by reyman** [comment]
Hi, I'm interested to run a docker image of zulip, and i see recently the PR you manage here : https://github.com/zulip/zulip/pull/450

What is the best option actually, wait and see for a merge on zulip repository ? or install directly your docker release / image ?

Thanks a lot for your work !
Rey.

**Comment by Galexrt** [comment]
@reyman I currently don't have an up to date status of the PR https://github.com/zulip/zulip/pull/450 and when it may get merged.

But a good way would be to use the image here, cause the version in the PR has less features (The PR doesn't contain the automatic backup and some other fancy stuff).

**Comment by reyman** [comment]
Ok :) 
And i suppose migration between the two images can be made later, so thanks :)

**Comment by Galexrt** [comment]
@reyman Migrating between them will **not** be possible!

My `galexrt/zulip` image uses different structures than the Docker image in the PR.
I would recommend you using this image here, because it has more features, like automatic backups.

**Comment by Galexrt** [comment]
Pushed the changes required for Zulip 1.3.10 to the branch `dev-1.3.10`.

**Comment by Galexrt** [comment]
Closing as #61 is the last issue to be resolved before the new release can be released.
