### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS - related to docker-zulip or jwilder/nginx-proxy ?

### ISSUE THREAD

**Issue by buyenne** [Galexrt/docker-zulip#59]
Hi,

Quick description of the configuration:

- got the docker-compose.yml configured, server ist running fine and accessible through https://ipv4:32xxx Port. I can add streams etc.
-  Only added **VIRTUAL_HOST: "zulip.mydomain.com"** for the reverse proxy.
- Ports 80 and 443 are used by jwilder/nginx-proxy
- Certs are fom Cacert and running fine with other subdomains.

The Problem is, I get ERR_TOO_MANY_REDIRECTS once I go to zulip.mydomain.com (which redirects to https)

Not sure where to look at currently. Configure the zulip NGINX? Oder something on the jwilder NGINX.

Your sincerly

Alexandre

**Comment by Galexrt** [comment]
What docker image version/tag are you using?

Could you please provide the access.log of the Zulip container and attach it as a gist. (To copy the access.log out of the container, use `docker cp ZULIP_CONTAINER_NAME:/var/log/nginx/access.log`)

**Comment by Galexrt** [comment]
What docker image version/tag are you using?

Could you please provide the access.log of the Zulip container and attach it as a gist. (To copy the access.log out of the container, use `docker cp ZULIP_CONTAINER_NAME:/var/log/nginx/access.log`)

**Comment by buyenne** [comment]
Docker version 1.10.1, build 9e83765

access.log: [https://gist.github.com/buyenne/0dcae1e6d96aaea98f2e#file-zulip_nginx_access-log](url)

cheers

Alexandre

**Comment by Galexrt** [comment]
Could you please provide the configuration/command you use to run jwilder nginx, so I can debug this on my site here. I think I almost know what the problem causes.

**Comment by buyenne** [comment]
Sure,

`docker run -d -p 80:80 -p 443:443 --name NGINX_Reverse_Proxy_SSL -v /etc/ssl/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

Pulled 24.02.2016

**Comment by Galexrt** [comment]
@buyenne I'm looking into it. Thanks for the informations!

**Comment by buyenne** [comment]
Your welcome. If I can help in some way, just ask.

**Comment by Galexrt** [comment]
@buyenne I haven't used `jwilder/nginx-proxy` in a long time. Do you need to set some flags or environment variables on the zulip container for the jwilder proxy to work?

**Comment by buyenne** [comment]
@Galexrt only one flag (environment vaiable) `VIRTUAL_HOST=subdomain.youdomain.com`

I have added this to the docker-compose.yml
`environment:
    VIRTUAL_HOST: "zulip.buyenne.com"
    DB_HOST: "database"
    MEMCACHED_HOST: "memcached"
    REDIS_HOST: "redis"
    RABBITMQ_HOST: "rabbitmq"`

**Comment by Galexrt** [comment]
@buyenne Could you post your full `docker-compose.yml` without any compromising data, so I can take a better look at the problem.

**Comment by buyenne** [comment]
@Galexrt - updated the gist

**Comment by buyenne** [comment]
I tried now the Variable "VIRTUAL_PROTO=https" to force the proxy to communicate with zulip only through https. Now I get a 502. Will do more tests.

**Comment by buyenne** [comment]
Got it!!!

Just add
` environment:
    VIRTUAL_HOST: "zulip.domain.com" /
    VIRTUAL_PROTO: "https" /
    VIRTUAL_PORT: "443"
`

**Comment by Galexrt** [comment]
Thanks for testing! 
That's good news to hear! I'm going to add this info to the wiki. 

Later I will add an option to disable https in the zulip container and disable the https redirect, so these options aren't needed, but it'll take some time to add this.

**Comment by Galexrt** [comment]
Added the info to the wiki. https://github.com/Galexrt/docker-zulip/wiki/Zulip-with-JWilder's-Nginx-Proxy
