### ISSUE TITLE
Blank login page

### ISSUE THREAD

**Issue by surajys** [Galexrt/docker-zulip#60]
I successfully registered 2 users. I got the registration mail also. 
If I click that link their profile page is opening. 
after logout I am unable to login again using browser . (There is no username password field)
For me login link is not working . if I click that link nothing is happing, only page will redirect to "https://zulip.example.com/login" No error message also. 
What is the issue ?

![loginissue](https://cloud.githubusercontent.com/assets/17525956/13378669/950e5f90-de33-11e5-9224-ab5123dc7591.png)

**Comment by Galexrt** [comment]
Could you please provide some logs from the container.
Run `docker exec -it ZULIP_CONTAINER_NAME /bin/bash`, run `cat /var/log/zulip/*` and post the output as a gist. Thanks!

**Comment by surajys** [comment]
zulip log files https://gist.github.com/surajys/84f108c1aef870b0ffe0

**Comment by surajys** [comment]
There is a problem with ```rabbitmq-server``` also. It is not starting properly. I removed ```rabbitmq-server``` including config files (```apt-get remove --purge rabbitmq-server```) . After that I run ```./root/zulip/scripts/setup/configure-rabbitmq``` script now ```rabbitmq``` is working .

**Comment by surajys** [comment]
If I continuously click login link it will generate these error messages in log files. 

![zulipauth](https://cloud.githubusercontent.com/assets/17525956/13380838/34a76518-de72-11e5-86a9-567b0bdbf189.png)

**Comment by Galexrt** [comment]
The messages in the picture aren't errors. 
They are just a server access log, that shows who has opened a page.

I'm looking into the error you have. 

What database image are you using? The default one from the `docker-compose.yml` or a custom one?

**Comment by surajys** [comment]
I am using default database.

**Comment by Galexrt** [comment]
@surajys Could you please manually post the output of All files in the container's `/var/log/zulip/` folder in the gist. It looks like you only posted one file's content.
(`docker exec -it ZULIP_CONTAINER_NAME /bin/bash` and do the `cat /var/log/zulip/FILE_NAME`)

**Comment by surajys** [comment]
Sorry I don't no how to use docker. What is "ZULIP_CONTAINER_NAME" means ? I will share all the log files.

**Comment by Galexrt** [comment]
Do you use `docker-compose` to start the container?
`ZULIP_CONTAINER_NAME` is the name of the container Zulip runs in.

**Comment by surajys** [comment]
I never used ```docker-compose```. I followed [official document](https://zulip.org/server.html) to configure Zulip, and I am using oracle VirtualBox for this. (for testing) .

**Comment by Galexrt** [comment]
What command do you use to run Zulip? Is it something like
`supervisorctl...` or `docker...`?

**Comment by surajys** [comment]
```supervisorctl```

**Comment by Galexrt** [comment]
You are at the wrong project. This is docker-zulip and not the Zulip Project. 
This is the Zulip Project: https://github.com/zulip/zulip. 

I'm closing this issue now, please create an Issue at the Zulip Project. 

BTW your problem seems to be related to a misconfiguration.
