### ISSUE TITLE
Zulip migration failed to v1.3.12

### ISSUE THREAD

**Issue by reyman** [galexrt/docker-zulip#68]
Hi,
I'm going to an old dev version to the new version `v1.3.12`

Here the full log 
https://gist.github.com/afb2570c30bb967ad53a538c143e5f3b

**Comment by galexrt** [comment]
Note to myself add `yes` pipe output to the migration command.

**Comment by galexrt** [comment]
@reyman I'm working on a fix.

**Comment by galexrt** [comment]
@reyman Please try again with the dev verson.
The new dev image should be built in about 30 minutes.

**Comment by galexrt** [comment]
Note to myself: If it still isn't working add `--noinput` option to the migrate command.
See https://docs.djangoproject.com/en/1.9/ref/django-admin/#django-admin-migrate.

**Comment by reyman** [comment]
Ok image start with dev version.

**Comment by galexrt** [comment]
I have added `--noinput` to the `manage.py migrate` `entrypoint.sh` script.

I'm closing this as it seems to be fixed.
