### ISSUE TITLE
Fix the rabbitmq-server (HOST) error

### ISSUE THREAD

**Issue by Galexrt** [Galexrt/docker-zulip#7]

**Comment by frankgerhardt** [comment]
Now that this issue is closed, is it fully working?

Would it make sense to remove the warning "WARNING! This is currently work in progress. It's not fully "working" yet." on the Docker hub page?

**Comment by Galexrt** [comment]
@frankgerhardt Yes, you are right, it should work now.
The Zulip Page shows and you can login to it.
I just need to make sure the container starts up without trouble after a restart, but the "first" time start the container works fine. I'll remove the "Warning" in one of the next commits.
Thanks for telling me!
