### ISSUE TITLE
docker-zulip uses depcreated 'link' for network linking

### ISSUE THREAD

**Issue by hasufell** [galexrt/docker-zulip#71]
https://docs.docker.com/compose/compose-file/#/upgrading

**Comment by galexrt** [comment]
From the [Upgrading](https://docs.docker.com/compose/compose-file/#/upgrading) Section:
> `links` with environment variables: As documented in the environment variables reference, environment variables created by links have been deprecated for some time. In the new Docker network system, they have been removed. You should either connect directly to the appropriate hostname or set the relevant environment variable yourself, using the link hostname:
> [...]

Only the environment variables have been deprecated/removed from the newer Docker network system.
So no problem for the current `docker-compose.yml` as the host vars are set and ports are the defaults.

**Comment by hasufell** [comment]
I think you misunderstood. I didn't say anything has been removed, but the `--link` approach is __legacy__ as outlined here: 
* https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/
* https://docs.docker.com/engine/userguide/networking/work-with-networks/#/linking-containers-in-user-defined-networks
* https://docs.docker.com/compose/compose-file/#/versioning

You are using a legacy docker-compose format with legacy network linking. That's not the up2date approach.

**Comment by galexrt** [comment]
Yes, I misunderstood you.
I have now updated the `docker-compose.yml` on the `dev` branch.
Could you please take a look and tell me if it is okay now. See the changes https://github.com/galexrt/docker-zulip/commit/f770ea91976784488a9d0130ad731e9e4ede39bd
From reading the pages you sent, I only see the environment variables from `links` in the `docker-compose.yml` being deprecated.

**Comment by hasufell** [comment]
You wouldn't use links at all in the new format, instead you would use networks: 
https://docs.docker.com/compose/networking/

> By default Compose sets up a single network for your app. Each container for a service joins the default
> network and is both reachable by other containers on that network, and discoverable by them at a
> hostname identical to the container name.

Also see the example on that page.

**Comment by galexrt** [comment]
As I'm understanding right now, just leaving the `links` out of the `docker-compose.yml` is enough.
Like this https://github.com/galexrt/docker-zulip/commit/06abaf9cbe02356588861032cfbc1652ee8bf125

**Comment by hasufell** [comment]
I guess so. Did you test it?

**Comment by galexrt** [comment]
I'm downloading the latest image right now and going to test it then.
I'll report back if it works like this.

**Comment by galexrt** [comment]
I entered the containers and pinged them. It's working without the `links`.

I'm going to merge these changes as soon as possible.

Thanks again for reporting this issue!
