### ISSUE TITLE
Can't create bots

### ISSUE THREAD

**Issue by xgodon** [galexrt/docker-zulip#84]
Hello i tried to install zulip with this yml file : 
 https://gist.github.com/xgodon/718f4f5d441802b6fd90ee47a4ea0a58

Then i set in /etc/zulip/settings.py
AUTH_LDAP_USER_SEARCH, AUTH_LDAP_BIND_DN AUTH_LDAP_SERVER_URI, EMAIL_HOST, MAIL_HOST_USER EMAIL_PORT EMAIL_USE_TLS 

So my chat is working, i can connect but when i try to create a bot in settings, the default end of the email adress is : 
 -bot@exemple.com@acme.com 
which is an incorrest adress, so i can't create them.

What did i fail to do? :/
Xavier

**Comment by galexrt** [comment]
@xgodon This issue is not related to docker-zulip.

Please create an issue at the official https://github.com/zulip/zulip project.
Also for documentation about Zulip, see the official docs: https://zulip.readthedocs.io/en/latest/index.html

**Comment by xgodon** [comment]
yeah sorry, i even found something at https://github.com/zulip/zulip/issues/3903 
thanks though.

**Comment by galexrt** [comment]
How do you set the options in the `settings.py`?
> Then i set in /etc/zulip/settings.py
> AUTH_LDAP_USER_SEARCH, AUTH_LDAP_BIND_DN AUTH_LDAP_SERVER_URI, EMAIL_HOST, MAIL_HOST_USER EMAIL_PORT EMAIL_USE_TLS

**Comment by galexrt** [comment]
Please update to `quay.io/galexrt/zulip:1.5.1-5` image!

***

Zulip options should be set like this as environment variables:
For `AUTH_LDAP_USER_SEARCH` setting, add this to the environment variables in the `docker-compose.yml`:
```
SETTING_AUTH_LDAP_USER_SEARCH: "YOUR_VALUE"
```
For other vars the same:
```
SETTING_EMAIL_USE_TLS: "True"
SETTING_MAIL_HOST_USER: "user@example.com"
```

**Comment by xgodon** [comment]
i tried but it didn't work.
maybe because i shouldn't have used :
LINK_SETTINGS_TO_DATA: "true"
MANUAL_CONFIGURATION: "true"
?

**Comment by galexrt** [comment]
@xgodon `MANUAL_CONFIGURATION` disables all configuration that is normally done automatically (the name says it all).
Disable `LINK_SETTINGS_TO_DATA` and `MANUAL_CONFIGURATION` and add the settings in the style: `SETTING_name` (where `name` is the key of the setting), just set the value to what you want to be set.

**Comment by xgodon** [comment]
yeah but what if i have to change something in the configuration file afterward?

**Comment by xgodon** [comment]
well i guell i'll work... oh i'm so dumb :')

**Comment by galexrt** [comment]
When you add new `SETTING_*` variables the config is always rebuilt on every start of the container.
