### ISSUE TITLE
Bot creation with bad email

### ISSUE THREAD

**Issue by huneau** [galexrt/docker-zulip#86]
Hi there, 

I think I found a bug with the docker version.
![docker bot](https://cloud.githubusercontent.com/assets/9199240/25136590/bf0243de-2455-11e7-836a-0ece0f84277a.png)

As you can see, the bot email has a concatenate domain.

I cannot try it on original zulip version, but I think you can easily see the bug.

**Comment by galexrt** [comment]
See https://github.com/zulip/zulip/issues/3903.

***

Closing as this is not an issue with the docker-zulip project.

**Comment by huneau** [comment]
thx and sry :)
