### ISSUE TITLE
Zulip:1.6.0-0 image isn't actually Zulip 1.6.0

### ISSUE THREAD

**Issue by pirate** [galexrt/docker-zulip#87]
I just ran `docker-compose stop; docker-compose rm; docker pull quay.io/galexrt/zulip:1.6.0-0; docker-compose up -d`.
```
Stopping dockerzulip_rabbitmq_1 ... done
Stopping dockerzulip_zulip_1 ... done
Stopping dockerzulip_memcached_1 ... done
Stopping dockerzulip_redis_1 ... done
Stopping dockerzulip_database_1 ... done
Going to remove dockerzulip_rabbitmq_1, dockerzulip_zulip_1, dockerzulip_memcached_1, dockerzulip_redis_1, dockerzulip_database_1
Are you sure? [yN] y
Removing dockerzulip_rabbitmq_1 ... done
Removing dockerzulip_zulip_1 ... done
Removing dockerzulip_memcached_1 ... done
Removing dockerzulip_redis_1 ... done
Removing dockerzulip_database_1 ... done
1.6.0-0: Pulling from galexrt/zulip
8f229c550c2e: Already exists
8e1fb71e8df6: Already exists
f75a34586856: Already exists
8744e322b832: Already exists
d5165bfce78f: Already exists
a3ed95caeb02: Pull complete
c2054a6bba02: Already exists
1af6d19325b3: Pull complete
9f87b8d34805: Pull complete
948664299d52: Pull complete
8f7a62ff39de: Pull complete
0f55c1a74f70: Pull complete
8c92d9a9e84b: Pull complete
Digest: sha256:eb2b8e4d40ff90f0af98d94034267e085d4b06145b70c414fba199f30c0f9f4a
Status: Downloaded newer image for quay.io/galexrt/zulip:1.6.0-0
Creating dockerzulip_redis_1
Creating dockerzulip_rabbitmq_1
Creating dockerzulip_memcached_1
Creating dockerzulip_zulip_1
Creating dockerzulip_database_1
```

It downloaded some new images and completed successfully, and Zulip came up fine afterwards.  The only problem is, Zulip is no different, it's running the same version as before with none of the v1.6.0 ui changes.
What can I do to get 1.6.0 running?  Thanks!

![screen shot 2017-06-07 at 2 35 05 pm](https://user-images.githubusercontent.com/511499/26897547-8c87412e-4b8e-11e7-894e-9f21d6fef503.PNG)

**Comment by galexrt** [comment]
@pirate Please repull the image and restart the Zulip instance before running the commands (to repull run: `docker pull quay.io/galexrt/zulip:1.6.0-0`).

Run the following command to verify the Zulip version you are running in the container:
```
docker exec -it YOUR_ZULIP_CONTAINER_ID_HERE su -- zulip -c "cat /home/zulip/deployments/current/version.py"
```
(Replace `YOUR_ZULIP_CONTAINER_ID_HERE` with the Zulip container name/id)

**Comment by pirate** [comment]
Aha, `docker ps` is showing `quay.io/galexrt/zulip:1.5.1-5` it appears I also have to update `docker-compose.yml` to point to the new images.

**Comment by galexrt** [comment]
Yes to use the new version of (Docker) Zulip you need to update the image in the `docker-compose.yml`.

Thank you for the wiki change!
