### ISSUE TITLE
db setup in kubernetes?

### ISSUE THREAD

**Issue by jmandel** [galexrt/docker-zulip#89]
I might just be missing something, but when I try to deploy the replicaset to a k8s cluster, it looks like the zulip container is [configured to talk to its podmates over hostnames like `postgres`](https://github.com/galexrt/docker-zulip/blob/master/kubernetes/zulip-rc.yml#L69-L70) rather than `localhost`. This prevents the zulip service from finding, e.g., the database.

Updating these to `localhost` works better but the zuplip container still gets stuck at

 >  "Could not connect to database server. Exiting."

... but when I manually exec into the zulip container I see that the db is indeed accessible:

```
#  /usr/bin/pg_isready -h "$DB_HOST" -p "$DB_HOST_PORT" -U "$DB_USER" -t 1 >/dev/null 2>&1
root@zulip-1-z46gs:/# echo $?
0
``` 

Is this related to some known issue?

**Comment by galexrt** [comment]
@jmandel Is the database in the same K8s pod context/in the same replicaset containers specified as Zulip?

**Comment by jmandel** [comment]
Yes, the db is in the same replicaset because I'm using the replication controller [defined in this repo](https://github.com/galexrt/docker-zulip/blob/master/kubernetes/zulip-rc.yml#L69-L70).

Looking back at the state 17h later: the pod is up and running. I'm a bit confused abut what happened, but will close this issue until/unless I can reproduce! Thanks for the response :-)

**Comment by galexrt** [comment]
@jmandel Good to hear the problem solved itself!
