### ISSUE TITLE
It's possible to use external Database ?

### ISSUE THREAD

**Issue by davaxi** [galexrt/docker-zulip#92]
Hi,

I try to install zulip with external PostgresSQL database. I remove database service and replace database connection info with my personal database. But when i try to up docker-compose, i have a bug on zulip who not access on postgresql files... 

How i can install zulip without quay.io/galexrt/postgres-zulip-tsearchextras:latest service ?

Thanks

**Comment by galexrt** [comment]
@davaxi You need to have the zulip `tsearch-extras` package installed on the postgres server you are using.
See https://zulip.readthedocs.io/en/1.6.0/dev-setup-non-vagrant.html#using-the-official-ubuntu-repositories-pgroonga-ppa-and-tsearch-extras-deb-package

**Comment by davaxi** [comment]
Thanks @galexrt

**Comment by galexrt** [comment]
@davaxi If there is anything else I can help you with, please let me know. :)
