### ISSUE TITLE
process-fts-updates and zulip-postsetup-create_user exits with status 1 and 2 respectively - then login failure

### ISSUE THREAD

**Issue by ledroide** [galexrt/docker-zulip#93]
Hi,
Trying many ways of login Zulip with user email and passwords defined in vars SETTING_ZULIP_ADMINISTRATOR, ZULIP_USER_EMAIL, ZULIP_USER_PASS ; I found these logs from dockerzulip_zulip_1 container - which should cause the "invalid password and email" message I get on Zulip web login page : 

```
zulip_1      | 2017-11-08 08:56:19,132 INFO success: zulip_events_digest_emails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1      | 2017-11-08 08:56:19,163 INFO exited: process-fts-updates (exit status 1; not expected)
zulip_1      | 2017-11-08 08:56:20,166 INFO spawned: 'process-fts-updates' with pid 622
zulip_1      | 2017-11-08 08:56:20,166 INFO success: zulip_events_user_activity entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1      | 2017-11-08 08:56:20,167 INFO success: zulip_events_error_reports entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1      | 2017-11-08 08:56:20,851 INFO exited: process-fts-updates (exit status 1; not expected)
zulip_1      | 2017-11-08 08:56:22,854 INFO spawned: 'process-fts-updates' with pid 696
zulip_1      | 2017-11-08 08:56:23,682 INFO exited: process-fts-updates (exit status 1; not expected)
zulip_1      | 2017-11-08 08:56:27,215 INFO spawned: 'process-fts-updates' with pid 718
zulip_1      | 2017-11-08 08:56:27,320 INFO exited: process-fts-updates (exit status 1; not expected)
zulip_1      | 2017-11-08 08:56:28,322 INFO gave up: process-fts-updates entered FATAL state, too many start retries too quickly
zulip_1      | 2017-11-08 08:56:41,135 INFO reaped unknown pid 710
zulip_1      | 2017-11-08 08:56:42,179 INFO exited: zulip-postsetup-create_user (exit status 2; not expected)
```

The problem looks similar to issues #23 and #66 - but their answers didn't help me.
I already tried after cleaning up containers, volumes, and local directories, like this : 

```
docker-compose down
docker container rm -f $(docker ps -qa)
docker volume rm $(docker volume ls -q)
docker network prune
sudo rm -r /opt/docker/zulip
```

Other variables such as SETTING_ADMIN_DOMAIN are of course already set. Using up-to-date checkout of this repo, calling image "quay.io/galexrt/zulip:1.7.0-1".

**Comment by stefanocog** [comment]
+1

**Comment by galexrt** [comment]
I have identified the issue and a fix is after my testing on it's way.

**Comment by galexrt** [comment]
@ledroide I have pushed a fix to the `dev` branch. You can see if the build is finished here: https://quay.io/repository/galexrt/zulip?tab=builds
I had to remove `zulip-postsetup-create_user` because commands used in, have been removed in the latest Zulip version.
To create an user you need to follow the new instructions in the README, see https://github.com/galexrt/docker-zulip/tree/dev#creating-zulip-user (the link is pointing to the dev branch right now).

Please let me know if that fixes the issue with `process_fts_updates`.

**Comment by ledroide** [comment]
@galexrt : There should be a mistake in documentation, or a lost executable : 

```
docker-zulip (master) * $ git checkout dev
Branch dev set up to track remote branch dev from origin.
Switched to a new branch 'dev'

docker-zulip (dev) * $ git log --since 0am
commit bb10045262278b32ebc623e3e0eec4a7f1033ec5 (HEAD -> dev, origin/dev)
Author: Alexander Trost <galexrt@googlemail.com>
Date:   Wed Nov 8 13:49:41 2017 +0100
    Corrected permission for createZulipRealm.sh
commit d8c08751ab0eeb616dd18731f908de47c9f36a1b
Author: Alexander Trost <galexrt@googlemail.com>
Date:   Wed Nov 8 12:14:24 2017 +0100
    Removed createZulipAdmin script
commit b289936a4588c2203fa1bc132a7a5a4fd06cb0ae
Author: Alexander Trost <galexrt@googlemail.com>
Date:   Wed Nov 8 11:49:55 2017 +0100
    Readded modified process_fts_updates script

docker-zulip (dev) * $ docker-compose exec zulip /opt/createZulipRealm.sh
oci runtime error: exec failed: container_linux.go:295: starting container process caused "exec: \"/opt/createZulipRealm.sh\": stat /opt/createZulipRealm.sh: no such file or directory"

docker-zulip (dev) * $ docker-compose exec zulip ls -l /opt/
total 4
-rwxr-xr-x 1 zulip zulip 1195 Jan  1  1980 createZulipAdmin.sh

docker-zulip (dev) * $ docker-compose exec zulip find / -type f -iname "*realm*" -executable

docker-zulip (dev) * $ docker-compose exec zulip find  / -type f -iname "*create*" -executable
/usr/lib/postgresql/9.5/bin/createlang
/usr/lib/postgresql/9.5/bin/createdb
/usr/lib/postgresql/9.5/bin/createuser
/usr/local/nvm/test/fast/Running "nvm use x" should create and change the "current" symlink
/usr/local/nvm/test/fast/Running "nvm use x" should not create the "current" symlink if $NVM_SYMLINK_CURRENT is false
/usr/local/nvm/test/fast/Running "nvm alias" should create a file in the alias directory.
/home/zulip/deployments/2017-11-02-10-12-39/scripts/lib/create-zulip-admin
/home/zulip/deployments/2017-11-02-10-12-39/scripts/lib/create-production-venv
/srv/zulip-venv-cache/28c46b2610f25e461725004503a2f0e9dc80c1a7/zulip-py3-venv/lib/python3.5/site-packages/zulip/examples/create-user
/srv/zulip-venv-cache/28c46b2610f25e461725004503a2f0e9dc80c1a7/zulip-py3-venv/bin/createfontdatachunk.py
/opt/createZulipAdmin.sh
```

Hope it helps

**Comment by galexrt** [comment]
@ledroide You only need to change the image used in your `docker-compose.yml` to test the fix: `quay.io/galexrt/zulip:dev`
The `docker-compose.yml` in the repo doesn't change depending on the branch.

**Comment by ledroide** [comment]
Sorry @galexrt for my wrng tag, now I use _dev_ tag for zulip image you just built.
I can now generate a URL to create a realm. 
Unfortunately, after completing my email address, is goes on timeout and displays "Internal server error". Tried ten times with variants, same result, timeout.
I tried also to execute `su zulip /home/zulip/deployments/current/manage.py generate_realm_creation_link` from the container, that gives another realm URL ; same result, and timeout.
No noticeable error or warning in logs during my tests.
However it looks better regarding _process-fts-updates_
```
zulip_1      | 2017-11-08 14:51:15,064 INFO spawned: 'process-fts-updates' with pid 543
zulip_1      | 2017-11-08 14:51:16,697 INFO success: process-fts-updates entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by galexrt** [comment]
@ledroide Do you set a valid SMTP server in the `docker-compose.yml`?

I get the email to validate my email address, follow the link, create an user and realm in the process, login and get a working Zulip instance.

**Comment by galexrt** [comment]
The issue about `zulip_deliver_enqueued_emails` is happening when Zulip tries to send an email over SMTP from an user not the login name depending on if the email server allows to send emails from account abc@example.com as xyz@example.com.
The error looks like this in the `/var/log/zulip/events_deliver_enqueued_emails.log`:
```
553, b'5.7.1 <galexrt@example.com>: Sender address rejected: not owned by user zulip@example.com'
```
and the logs from the container look like this:
```
zulip_1      | 2017-11-08 15:57:30,652 INFO exited: zulip_deliver_enqueued_emails (exit status 1; not expected)
zulip_1      | 2017-11-08 15:57:31,655 INFO spawned: 'zulip_deliver_enqueued_emails' with pid 1109
zulip_1      | 2017-11-08 15:57:32,658 INFO success: zulip_deliver_enqueued_emails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

So keep that in mind when configuring the SMTP server, that it should allow the zulip email user to send as other users/email addresses too.

**Comment by ledroide** [comment]
Sorry for the delay, but it still fails at realm creation, with message 
"Configuration error
It appears there are problems with the email configuration.
See /var/log/zulip/errors.log for more details on the error."
```
$ docker-compose exec zulip bash 
root@126873949aab:/# nc -zvw1 $SETTING_EMAIL_HOST $SETTING_EMAIL_PORT
gai-luron [172.31.4.232] 25 (?) open
root@126873949aab:/# tail /var/log/zulip/errors.log
2017-11-10 10:57:37.746 ERR  [] Error in create_realm: STARTTLS extension not supported by server.
```
Tried on both ports http and https, same error

**Comment by galexrt** [comment]
@ledroide From your comment that you seem to have deleted, the message `STARTTLS extension not supported by server.` means that Zulip tries to use `STARTTLS` to connect to your SMTP server.
Try disabling this by setting the env var `SETTING_EMAIL_USE_TLS` to `false` (and maybe add the env var `SETTING_EMAIL_USE_SSL` to `false` too).

The whole SMTP env vars can be found here: https://github.com/galexrt/docker-zulip/wiki/Zulip-Email-SMTP-Configuration (the defaults specified in the wiki seem outdated by upstream changes from Zulip).

**Comment by galexrt** [comment]
@ledroide @stefanocog Does this issue still appear for you with `dev` or `1.7.0-2` image and a working SMTP configuration set?

**Comment by ledroide** [comment]
@galexrt : I'm testing zulip from my office, where smtp and ldap settings are highly complex, so I'm unable to automate or even solve this issue from a container. I also tried davmail as a proxy, and it failed.
I was guessing ZULIP_USER_EMAIL and ZULIP_USER_PASS would create a usable zulip user, obviously I was wrong. It looks like there is no way to use zulip with a standalone authentication. If this is the case, I can't help solving this issue anymore. Sorry for this.

**Comment by galexrt** [comment]
@ledroide Sorry but the `ZULIP_USER_EMAIL` and `ZULIP_USER_PASS` have been deprecated in docker-zulip because Zulip doesn't allow "manual" realm creation anymore. Due to this change in Zulip creating an user via `manage.py` in Zulip requires a realm to exist and only prints out an URL to create an user together with a realm.

**Comment by galexrt** [comment]
@ledroide I'm going to close this issue for now.
As written I'm not experiencing this with a SMTP server set correctly.

About creating an user without a SMTP server, you could ask at the official Zulip chat: https://chat.zulip.org/
