### ISSUE TITLE
env PUSH_NOTIFICATION_BOUNCER_URL is not added to setting.py

### ISSUE THREAD

**Issue by TomaszN007** [galexrt/docker-zulip#96]
When i add SETTING_PUSH_NOTIFICATION_BOUNCER_URL as a env is not added at the bottom of settings.py.

**Comment by galexrt** [comment]
@TomaszN007 Can you try running the image with the `DEBUG: "true"` env var and check if the log output contains the `SETTING_PUSH_NOTIFICATION_BOUNCER_URL`
Also please post the log output (without any passwords in it) here

**Comment by galexrt** [comment]
@TomaszN007 Also have you checked the `settings.py` in `/etc/zulip` and the one in the `/home/zulip/deployments/current/...` directory?

**Comment by timabbott** [comment]
`SETTING_PUSH_NOTIFICATION_BOUNCER_URL` should work (and I just tested it gets added properly).  Closing, I added ee0a7cb9cad2509383f44c783070cc84433348c2 to make it clear how to do this.
